![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/2560px-Pandas_logo.svg.png" width="500" height="200" />

- Funções Úteis II
  - map
  - apply
  - applymap

**Bora pra aula?**

In [ ]:
!pip install pandas
!pip install numpy

In [1]:
import pandas as pd
import numpy as np

# Funções Úteis

In [2]:
df_pokemons = pd.read_csv('pokemon_data.csv')
df_pokemons

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

Suponha que precisamos alterar o nome dos pokémons, adicionando o pré-fixo "Pokémon" em seus nomes, separando por underline.
**Ex.: Pokémon_Bulbasaur**

---
**Revisão Relâmpago de Funções**

Uma função é um bloco de código que recebe alguns parâmetros e retorna um valor. Ex.: Podemos receber a quantidade de horas trabalhadas e o valor da hora de um funcionário e retornar por meio da função o salário daquele mês.

Para definir uma função precisamos da palavra-chave ```def``` . Além da ```def```, precisamos dar um nome a nossa função. No nosso caso ela irá se chamar calcular_salário. Por fim, ela irá receber 2 parâmetros: quantidade de horas trabalhadas e valor da hora, e então retornar o valor calculado através da palavra-chave ```return```.

In [3]:
def calcular_salario(valor_da_hora, horas_trabalhadas):
    salario_do_mes = valor_da_hora*horas_trabalhadas
    return salario_do_mes

In [4]:
calcular_salario(10, 100)

1000

In [5]:
calcular_salario(200, 200)

40000

---

Vamos usar uma função para adicionar o pré-fixo "Pokémon" a qualquer string e return a nova string.

In [6]:
def adicionar_pokemon(string):
    nova_string = "Pokémon_"+string
    return nova_string

In [7]:
adicionar_pokemon('Thiago')

'Pokémon_Thiago'

In [8]:
adicionar_pokemon('Bulbasaur')

'Pokémon_Bulbasaur'

In [9]:
adicionar_pokemon('Ivysaur')

'Pokémon_Ivysaur'

Agora, basta nós aplicarmos essa função para todos os pokémons do nosso data frame. Como faríamos isso?

Uma opção seria por meio de um ```for```.  Mas a opção mais legal seria utilizar o método ```map```.

In [10]:
%%timeit
df_pokemons['Nome-Novo'] = df_pokemons['Name'].map(adicionar_pokemon)

122 µs ± 4.02 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [11]:
%%timeit
nomes = []
for name in df_pokemons['Name']:
    nomes.append(adicionar_pokemon(name))
df_pokemons['Nome-Novo'] = nomes

169 µs ± 9.18 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [12]:
df_pokemons.shape

(800, 13)

## `map`

O método map irá percorrer item por item e aplicar a função desejada. Exemplo: Tirar a raíz quadrada de cada elemento. Note que já existe uma função que realiza essa tarefa. A criação de funções com ```def``` será para apenas para o caso de funções bem personalizadas. No Numpy temos o ```np.sqrt```.

**Resumo:**

- **Aplicado a:** `Series`.<br>
- **Propósito:** `map()` aplica uma função a cada elemento de uma `Series`. Pode ser usado para transformar valores de uma coluna com base em uma função, dicionário, ou uma série de substituições.<br>
- **Observação:** `map()` é especialmente útil para substituições baseadas em mapeamentos, como transformar categorias em valores numéricos usando um dicionário.

In [14]:
# Tirar a raíz  de cada elemento da coluna HP
df_pokemons['HP'].map(np.sqrt)

0      6.708204
1      7.745967
2      8.944272
3      8.944272
4      6.244998
         ...
795    7.071068
796    7.071068
797    8.944272
798    8.944272
799    8.944272
Name: HP, Length: 800, dtype: float64

## `apply`

Se quisermos aplicar uma determinada função em todas as linhas de uma vez? Ou em todas as colunas?.<br>
Use o ```apply```.

**Resumo:**

- **Aplicado a:** `Series` e `DataFrame`.<br>
- **Propósito:** `apply()` permite aplicar uma função a cada elemento de uma Series ou a cada coluna (ou linha) de um DataFrame.<br>
- **Observação:** No contexto de `DataFrames`, o parâmetro `axis` pode ser usado para especificar se a função deve ser aplicada por linha (axis=1) ou por coluna (axis=0, que é o padrão).

In [15]:
%%timeit
df_pokemons['Nome-Novo'] = df_pokemons['Name'].map(adicionar_pokemon)

126 µs ± 6.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [16]:
%%timeit
df_pokemons['Nome-Novo'] = df_pokemons['Name'].apply(adicionar_pokemon)

136 µs ± 9.62 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [19]:
# APlicando a função max para cada coluna
df_pokemons[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']].max(axis=0)

HP         255
Attack     190
Defense    230
Sp. Atk    194
Sp. Def    230
Speed      180
dtype: int64

In [18]:
# APlicando a função max para cada linha
df_pokemons[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']].max(axis=1)

0       65
1       80
2      100
3      123
4       65
      ...
795    150
796    160
797    150
798    170
799    130
Length: 800, dtype: int64

Note que o valor máximo de cada linha foi retornado.

Porém, existem funções que não têm esse comportamento. Suponha que queiramos saber a diferença entre o máximo e o mínmo de cada atributo do nosso dataframe.

In [20]:
def max_min(x):
    diferenca = x.max() - x.min()
    return diferenca

No nosso exemplo, o x é uma coluna do dataframe. Pra aplicar essa lógica de cálculo em uma coluna, usamos o ```apply```.

In [21]:
# Aplicando o método para algumas colunas
df_pokemons.loc[:, ['HP', 'Sp. Atk']].apply(max_min)

HP         254
Sp. Atk    184
dtype: int64

In [22]:
df_pokemons[['HP', 'Sp. Atk']].apply(max_min)

HP         254
Sp. Atk    184
dtype: int64

In [23]:
# Checando
max_HP = df_pokemons['HP'].max()
min_HP = df_pokemons['HP'].min()
max_SP_Atk = df_pokemons['Sp. Atk'].max()
min_SP_Atk = df_pokemons['Sp. Atk'].min()

In [24]:
# Diferença entre o máximo e mínimo HP
max_HP - min_HP

254

In [25]:
# Diferença entre o máximo e o mínimo HP
max_SP_Atk - min_SP_Atk

184

## `applymap`

E se quisermos aplicar alguma transformação para cada elemento do dataframe de uma única vez? <br>
Use applymap.

**Resumo:**

- **Aplicado a:** `DataFrame`.<br>
- **Propósito:** `applymap()` é usado exclusivamente em `DataFrames` para aplicar uma função a cada elemento individualmente. É semelhante ao `apply()`, mas ao invés de aplicar a função a colunas ou linhas inteiras, aplica a cada elemento do `DataFrame`.
- **Observação:** `applymap()` é ideal para operações que precisam ser aplicadas a cada elemento de um DataFrame, como formatar valores, aplicar transformações matemáticas, etc.

In [26]:
# Aplicar a raíz quadrada em todos os elementos
df_pokemons.loc[:, ['HP', 'Sp. Atk', 'Attack', 'Defense']].applymap(np.sqrt)

/var/folders/zm/3bssg1p14lj63wq1qny6y2qh0000gn/T/ipykernel_10200/2502591926.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_pokemons.loc[:, ['HP', 'Sp. Atk', 'Attack', 'Defense']].applymap(np.sqrt)

           HP    Sp. Atk     Attack    Defense
0    6.708204   8.062258   7.000000   7.000000
1    7.745967   8.944272   7.874008   7.937254
2    8.944272  10.000000   9.055385   9.110434
3    8.944272  11.045361  10.000000  11.090537
4    6.244998   7.745967   7.211103   6.557439
..        ...        ...        ...        ...
795  7.071068  10.000000  10.000000  12.247449
796  7.071068  12.649111  12.649111  10.488088
797  8.944272  12.247449  10.488088   7.745967
798  8.944272  13.038405  12.649111   7.745967
799  8.944272  11.401754  10.488088  10.954451

[800 rows x 4 columns]

## Resumo das Diferenças:

`map()`: Usado em `Series` para aplicar uma função a cada elemento individualmente. Útil para substituições e transformações simples.<br>

`apply()`: Usado em `Series` ou `DataFrames` para aplicar uma função a colunas, linhas inteiras, ou a cada elemento, dependendo do contexto (com `axis=0` ou `axis=1` para `DataFrames`).<br>

`applymap()`: Usado exclusivamente em `DataFrames` para aplicar uma função a cada elemento individualmente. É como um `apply()` para cada célula do DataFrame.